apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secure-kuber-master-vm-shop
  namespace: default
spec:
  secretName: secure-kuber-master-vm-shop-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kuber-master-vm-shop
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
