apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.service_port }}
      targetPort: {{ .Values.service.target_port }}
  selector:
    app: "{{ .Values.name }}"